 export const ADD_TO_CART='ADD_TO_CART';
export const REMOVE_FROM_CART='REMOVE_FROM_CART';
export const UPDATE_CART_QTY='UPDATE_CART_QTY'
export const DELETE_FROM_CART='DELETE_FROM_CART'
export const RESET_CART='RESET_CART'
export const SAVE_SHIPPING_ADDRESS='SAVE_SHIPPING_ADDRESS'
export const SAVE_PAYMENT_METHOD='SAVE_PAYMENT_METHOD'