export const ORDER_FETCH_REQUEST='ORDER_FETCH';
export const ORDER_FETCH_SUCCESS='ORDER_FETCH_SUCCESS';
export const ORDER_FETCH_FAIL='ORDER_FETCH_FAIL';
export const ORDER_PAY_REQUEST='ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCESS='ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL='ORDER_PAY_FAIL';
export const ORDER_PAY_RESET='ORDER_PAY_RESET';
export const ORDER_LIST_REQUEST='ORDER_LIST_REQUEST';
export const ORDER_LIST_SUCCESS='ORDER_LIST_SUCCESS';
export const ORDER_LIST_FAIL='ORDER_LIST_FAIL';

